<!DOCTYPE html>
<html lang="en-us" dir="ltr" itemscope itemtype="http://schema.org/Article">

  
  
      
  
      
  

  <head>
  <meta charset="utf-8" />

  
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Blogue do Caloni - Try-catch flutuante</title>
  <meta name="author" content="" />

  <meta name="generator" content="Hugo 0.67.1" />

  
  <meta property="og:title" content="Try-catch flutuante"/>
  <meta property="og:type"
        content="article"/>
  <meta property="og:url" content="http://www.caloni.com.br/try-catch-flutuante/"/>
  <meta property="og:image"
        content="/img/author.jpg"/>
  <meta property="og:description"
        content="Esse detalhe da linguagem quem me fez descobrir foi o Yorick, que costuma comentar no blogue e tive o prazer de conhecer no 4o. EPA-CCPP.
É possível, apesar de bizarro, colocar um bloco try-catch em..."/>

  
  <link href="" rel="feed" type="application/rss+xml"
        title="Blogue do Caloni"/>

  
  
  <link rel="stylesheet" type="text/css" href="/css/custom.css"/>
  <link rel="stylesheet" type="text/css" href="/css/jquery-ui.css"/>

  
  <script src="/js/jquery-1.10.2.js"></script>
  <script src="/js/jquery-ui.js"></script>
  
    <script src="/js/list.js"></script>
  

  
  <link rel="icon" href="/img/favicon.ico"/>
  </head>


  <body style="min-height:100vh;display:flex;flex-direction:column">

    <nav class="navbar has-shadow is-white"
     role="navigation" aria-label="main navigation">

  <div class="container">

    <div class="navbar-brand">
        <img alt="Brand" src="/img/brand.svg">
        &nbsp;
        <a class="navbar-item" title="Go to Home" href="/">
            <div class="is-6">Blogue do Caloni</div>
        </a>
    </div>

    

  </div>
</nav>


      
      <div class="container">
        <p class="title">

Try-catch flutuante

</p>

        

        
          <div class="content">

            
              <p>Esse detalhe da linguagem quem me fez descobrir foi o Yorick, que costuma comentar no blogue e tive o prazer de conhecer no <a href="/epa-ccpp-4-nossa-comunidade-ganhando-forma">4o. EPA-CCPP</a>.</p>
<p>É possível, apesar de bizarro, colocar um bloco try-catch em torno da lista de inicialização de variáveis de um construtor. Essa característica da linguagem permite que possamos capturar alguma exceção lançada por algum construtor de algum membro da classe. A construção em código ficaria no estilo abaixo:</p>
<pre><code>Class::Class() try : initialization-list
{
    // Class constructor body
}
catch(...) // note: this IS right!
{
    // do something about
    // just like &quot;throw&quot; over here
}
</code></pre>
<p>Apesar dessa capacidade, não conseguimos parar o lançamento da exceção. Após seu lançamento, caímos no bloco catch abaixo do corpo do construtor e a exceção é lançada novamente, como se houvesse uma intrução throw no final do catch.</p>
<p>O exemplo abaixo demonstra um código de uma classe que captura a exceção durante a inicialização dos membros. Na seguida o catch da função main é executada, provando que a exceção de fato não é &quot;salva&quot; no primeiro bloco.</p>
<pre><code>#include &lt;iostream&gt;

/* This class explodes */
class Explode
{
    public:
        Explode(int x) 
        {
            m_x = x;
            throw x;
        }

        void print()
        {
            std::cout &lt;&lt; &quot;The number: &quot; &lt;&lt; m_x &lt;&lt; std::endl;
        }

    private:
        int m_x;
};

/* This class is going to be exploded */
class Victim
{
    public:
        Victim() try : m_explode(5)
        {
            std::cout &lt;&lt; &quot;You're supposed to NOT seeing this...\n&quot;;
        }
        catch(...) 
        { 
            std::cerr &lt;&lt; &quot;Something BAD hapenned\n&quot;;
            std::cerr &lt;&lt; &quot;We're going to blow up\n&quot;;
            // just like 'throw' over here
        }

        void print()
        {
            m_explode.print();
        }

    private:
        Explode m_explode;
};

int main()
{
    try
    {
        Victim vic;
    }
    catch(...)
    {
        std::cerr &lt;&lt; &quot;Something BAD BAD happenned...\n&quot;;
    }
}
</code></pre>
<p>Testei esse código nos seguintes compiladores:</p>
<ul>
<li>Visual Studio 6. Falhou, demonstrando desconhecer a sintaxe.</li>
<li>Borland C++ Builder 5. Falhou, demonstrando desconhecer a sintaxe.</li>
<li>Borland Developer Studio 4. Falhou, com o mesmo erro.</li>
<li>Visual Studio 2003. Comportamento esperado.</li>
<li>Visual Studio 2005. Comportamento esperado.</li>
<li>Visual Studio 2008. Comportamento esperado.</li>
<li>G++ (no Cygwin). Comportamento esperado.</li>
</ul>
<p>A saída esperada é a seguinte:</p>
<pre><code>Something BAD hapenned
We're going to blow up
Something BAD BAD happenned...
</code></pre>

            

          </div>

        <div class="taglist">
            <p class="author">

  Wanderley Caloni,
  
    
  
    
  
  <a href="https://github.com/Caloni/blog/blob/master/content/posts/try-catch-flutuante.md">2008-04-03 00:00:00 &#43;0000</a>

</p>

            
      <a href="/categories/ccpp">ccpp</a> 
    
    <a class="externalgray" href="https://t.me/bloguedocalonidiscuss">discuss</a>


        </div>

      </div>

  </body>

</html>
